source "https://rubygems.org"
  gem "rails", "~> 6.1.3"
  gem "redis", "~> 4.2.5"
  gem "cable_ready", "~> 4.5.0"
  gem "stimulus_reflex", "~> 3.4.1"
  gem "puma", "~> 5.2.2"
  gem "activerecord-nulldb-adapter"
  gem "view_component", require: "view_component/engine"
  gem "view_component_reflex"